### ISSUE TITLE
Multiple SRA to FASTQ conversion issue

### ISSUE THREAD

**Issue by langouec** [rvalieris/parallel-fastq-dump#4]
Hello,

This might be a novice problem but when I try to do the conversion of multiple files within a SRA group (i.e. SRA227673, 33 files) I get 0 byte files... I can get the FASTQ files when I do individual files. I am using iMac desktop and terminal version 2.7.3. The way I tried doing multiple files is like:

$ parallel-fastq-dump --split-3 --outdir out/ ---sra-id SRR174709[0-9] 

I did [#] for the last one because within this range there is 2 files (wanted to test to see if it worked before trying to do 33 files). Any help will be greatly appreciated!!

**Comment by rvalieris** [comment]
hello,

so if I understood correctly, you are trying to dump multiple SRRs at once, right ?
sorry but this won't work, as it currently is implemented the tool will only take a single SRR at a time.

as for the output files being 0 bytes, that sounds like a bug on fastq-dump itself, please post the output logs of what you tried here, but I think this is the bug: https://github.com/ncbi/sra-tools/issues/93

edit: to explain better whats going on, when fastq-dump exits with a error parallel-fastq-dump will not use the output files, because there is no way to know if the output is correct, thats why it shows up as 0 bytes.

**Comment by rvalieris** [comment]
I added support for downloading multiple SRR ids on the latest version, so this should work with version 0.6.0
