### ISSUE TITLE
Upgrade to sra toolkit 3.0

### ISSUE THREAD

**Issue by marina-yurieva** [rvalieris/parallel-fastq-dump#46]
Could you please upgrade your tool to use fastq-dump from sra toolkit 3.0? NCBI changed something, and some sra runs can only be downloaded with the new version of the toolkit (for example, try SRR15808775. It works with 3.0 but has "access denied" with the earlier version or any other methods of downloading). And with the new toolkit version I cannot use the parallel wrapper.

Thank you!

**Comment by rvalieris** [comment]
hello,

I tried to download SRR15808775 with the current version I have (sra-tools 2.11.0) and it worked, so I'm not sure whats the issue exactly.

if you can reproduce this "access denied" error with fastq-dump I think you should go talk directly with the sra-tools authors because it sounds like a regression or it could be some configuration issue.
